version: '3'
services:
  web:
    build: .
  mongodb:
    image: "mongo"
  mongo-express:
    image: "mongo-express"
    environment:
     - ME_CONFIG_MONGODB_PORT=27017
     - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
     - "8082:8081"