apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-express
  name: mongo-express
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: mongo-express
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
