apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: c:\dev\programms\kompose-windows-amd64.exe convert -f docker-compose.yml
      --provider=openshift
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-express
  name: mongo-express
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8081
  selector:
    io.kompose.service: mongo-express
status:
  loadBalancer: {}
