apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: c:\dev\programms\kompose-windows-amd64.exe convert -f docker-compose.yml
      --provider=openshift
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    io.kompose.service: mongodb
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
      - image: ' '
        name: mongodb
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - mongodb
      from:
        kind: ImageStreamTag
        name: mongodb:latest
    type: ImageChange
status: {}
