apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: web
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
